#!/usr/bin/env bash

swap=`free | tail -1`

total=`echo $swap | awk '{print $2}'`

used=`echo $swap | awk '{print $3}'`

used2=$(echo "scale=2;${used}/${total}"|bc -l)

used_perc=$(echo "scale=2;${used2}*100"|bc -l)

if [ $used_perc -lt 80 ];then
  echo "<span foreground='#ffffff' ><sup>swap</sup> $used_perc%</span>"
    elif [ $used_perc -gt 80 ];then
         echo "<span foreground='#ff0000' ><sup>swap</sup> $used_perc%</span>"
fi
