#!/usr/bin/env bash

# a volume icon setter using /usr/lib/i3blocks/volume

volumevalue=`/usr/lib/i3blocks/volume`
volumevaluewopercent=`echo $volumevalue | sed 's/\%//g'`

if [ "$volumevaluewopercent" == "MUTE" ] || [ "$volumevaluewopercent" == "0" ]; then 
	echo " $volumevalue"
elif [ "$volumevaluewopercent" -gt "0" ] && [ "$volumevaluewopercent" -lt "50" ]; then
	echo " $volumevalue"
elif [ "$volumevaluewopercent" == "50" ]; then
	echo " $volumevalue"
elif [ "$volumevaluewopercent" -gt "50" ]; then
	echo " $volumevalue"
fi
