#!/usr/bin/env bash

WIRELESS_CHECK=$(nmcli -t -f active,ssid dev wifi | egrep '^yes' | cut -d\' -f2)

INTERFACE_NAME=$(ip route get 8.8.8.8 | sed -nr 's/.*dev ([^\ ]+).*/\1/p')
WIRELESS_STRENGTH=$(awk 'NR==3 {print $3+10 "%"}''' /proc/net/wireless)
if [ -z $WIRELESS_CHECK ]; then
   echo " $INTERFACE_NAME"
    elif [ ! -z $WIRELESS_CHECK ]; then
        echo " $INTERFACE_NAME     $WIRELESS_STRENGTH"
    else
      echo " $INTERFACE_NAME"
      fi
